version: '3.1'
services:
    mysql-server:
       image: mysql:5.7
       container_name: mysql-server
       network_mode: host
       ports:
         - 3306:3306
       restart: always
       environment:
         - MYSQL_DATABASE=zabbix
         - MYSQL_USER=zabbix
         - MYSQL_PASSWORD=zabbix
         - MYSQL_ROOT_PASSWORD=zabbix
       volumes:
         - /etc/localtime:/etc/localtime
    zabbix-server-mysql:
       image: zabbix/zabbix-server-mysql:latest
       container_name: zabbix-server-mysql
       network_mode: host
       ports:
         - 10051:10051
       environment:
         - DB_SERVER_HOST=127.0.0.1
         - MYSQL_DATABASE=zabbix
         - MYSQL_USER=zabbix
         - MYSQL_PASSWORD=zabbix
         - MYSQL_ROOT_PASSWORD=zabbix
       volumes:
         - /etc/localtime:/etc/localtime
       depends_on:
         - mysql-server
    zabbix-web-nginx-mysql:
       image: zabbix/zabbix-web-nginx-mysql:siang
       container_name: zabbix-web-nginx-mysql
#       network_mode: host
       ports:
         - 8080:80
       environment:
         - DB_SERVER_HOST=172.16.106.130
         - DB_SERVER_PORT=3306
         - MYSQL_DATABASE=zabbix
         - MYSQL_USER=zabbix
         - MYSQL_PASSWORD=zabbix
         - MYSQL_ROOT_PASSWORD=zabbix
         - PHP_TZ=Asia/Taipei
       volumes:
         - /etc/localtime:/etc/localtime
       depends_on:
         - mysql-server
         - zabbix-server-mysql
