---
apiVersion: v1
kind: Service
metadata:
  name: ksfka-metrics-svc
  namespace: monitor
  labels:
    app: kafka-metrics-svc
spec:
  ports:
  - port: 7072
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: monitor
  labels:
    app: kafka-exporter
spec:
  ports:
    - port: 9308
      protocol: TCP
      targetPort: 9308
  selector:
    app: kafka-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: zk-metrics-svc
  namespace: monitor
  labels:
    app: zk-svc
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-exporter
  namespace: monitor
  labels:
    app: zookeeper-exporter
spec:
  ports:
    - port: 9141
      protocol: TCP
      targetPort: 9141
  selector:
    app: zookeeper-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-monitor-nodeport
  namespace: monitor
  labels:
    app: prometheus-monitor-nodeport
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 31124
  selector:
    app: prometheus-zk-kafka
