apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "node-exporter"
  namespace: "prometheus"
  labels:
    k8s-app: "node-exporter"
    stage: "all"
    class: "system"
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: node-exporter
  namespaceSelector:
    matchNames:
    - prometheus
  endpoints:
  - port: http
    scheme: http
    interval: 30s

