apiVersion: v1
kind: Service
metadata:
  labels:
    app: "node-exporter-datanode"
    k8s-app: "node-exporter-datanode"
    monitor: "on"
    class: "system"
  name: "node-exporter-datanode"
  namespace: "prometheus"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 9100
    protocol: TCP

