apiVersion: v1
kind: Endpoints
metadata:
  name: "node-exporter-datanode"
  namespace: "prometheus"
subsets:
- addresses:
  - ip: 10.22.20.13
  - ip: 10.22.21.13
  ports:
  - name: http
    port: 9100
    protocol: TCP
