apiVersion: v1
kind: Service
metadata:
  name: influxdb-nodeport
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "InfluxDB"
spec:
  type: NodePort
  ports:
    - name: api
      port: 8086
      targetPort: 8086
      nodePort: 31122
  selector:
    k8s-app: influxGrafana
