global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      server: 'global-monitor'
scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="node-exporter-work1"}'
        - '{job="node-exporter-work2"}'
        - '{job="node-exporter-work3"}'
        - '{job="node-exporter-work4"}'
        - '{job="gateway"}'
        - '{job="docker-daemon"}'
    static_configs:
      - targets:
        - '10.22.14.11:31121'
        - '10.22.15.11:31119'
        - '10.22.15.11:31123'
