global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      server: 'global-monitor'
scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="node-exporter-master1"}'
        - '{job="node-exporter-master2"}'
        - '{job="node-exporter-work1"}'
        - '{job="node-exporter-work2"}'
        - '{job="node-exporter-work3"}'
        - '{job="node-exporter-work4"}'
        - '{job="gateway"}'
        - '{job="docker-daemon"}'
    static_configs:
      - targets:
        - '10.22.14.11:31121'
        - '10.22.15.11:31119'
        - '10.22.15.11:31123'
  - job_name: 'elasticsearch'
    scrape_interval: 60s
    scrape_timeout:  30s
    metrics_path: "/metrics"
    static_configs:
    - targets:
      - 10.22.14.13:9108
      - 10.22.15.13:9108
      labels:
        service: elasticsearch
    relabel_configs:
    - source_labels: [__address__]
      regex: '(.*)\:9108'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: [__address__]
      regex:         '.*\.(.*)\.lan.*'
      target_label:  'environment'
      replacement:   '$1'
