version: "3"
services:
  prom:
    image: siangyeh8818/prometheus-docker:2.6
#    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
     - ./monitor/prometheus.yml:/prometheus/prometheus.yml
     - /etc/localtime:/etc/localtime
     - /opt/prometheus-global:/opt/prometheus
    privileged: true
    ports:
     - 9090:9090
    depends_on:
     - exporter
     - nginx
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 190M
    restart: always
  exporter:
    image: prom/node-exporter:latest
    ports:
     - "9100:9100"
    network_mode: host
  grafana:
    image: siangyeh8818/grafana-openfaas:4.3.2
    ports:
     - "3000:3000"
    depends_on:
      - prom
      - nginx
    env_file:
    - ./grafana.env
    volumes:
    - /etc/localtime:/etc/localtime
#  alertmanager:
#    image: prom/alertmanager
#    volumes:
#      - ./monitor/alertmanager.yml:/etc/alertmanager/alertmanager.yml
#    depends_on:
#      - configuration_manager
#    command:
#      - -config.file=/etc/alertmanager/alertmanager.yml
  nginx:
#     image: nginx:test-1
     image: siangyeh8818/nginx:influx-prom
     restart: always
     ports:
       - "31122:31122"
       - "31119:31119"
       - "31121:31121"
     privileged: true
     env_file:
     - ./nginx.env
     volumes:
     - /etc/localtime:/etc/localtime
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379


