version: "3"
services:
  prom:
    image: siangyeh8818/prometheus-docker:2.6
#    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
     - ./monitor/prometheus-global.yml:/prometheus/prometheus.yml
     - /etc/localtime:/etc/localtime
     - /opt/prometheus-global:/opt/prometheus
    privileged: true
    ports:
     - 9090:9090
    depends_on:
     - exporter
  exporter:
    image: prom/node-exporter:latest
    ports:
     - "9100:9100"
    network_mode: host
  grafana:
    image: siangyeh8818/grafana-openfaas:4.3.3
    ports:
     - "3000:3000"
    depends_on:
      - prom
    env_file:
    - ./grafana.env
