apiVersion: v1
kind: Service
metadata:
  name: k8s
  namespace: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 32767
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: k8s
