apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: prometheus
spec:
  serviceMonitorSelector:
    matchExpressions:
    - key: class
      operator: In
      values:
      - system
      - all
  serviceAccountName: prometheus-k8s
  retention: 90d
  resources:
    requests:
      memory: 400Mi
