apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter-master
  name: node-exporter-master
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    k8s-app: node-exporter-master
