global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      server: 'global-monitor'
scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~"prometheus.*"}'
        - '{job="docker"}'
        - '{job="node"}'
    static_configs:
      - targets:
        - 'localhost:9091'
        - 'localhost:9092'
