version: "3"
services:
  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:1.0.2
    command:
     - '-es.uri=http://172.17.0.1:9200'
    restart: always
    ports:
    - "127.0.0.1:9108:9108"
