kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus-conf-system
  namespace: kube-system
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      external_labels:
          monitor: 'node-monitor'
    rule_files:
        - 'alert.rules.yml'
    scrape_configs:
      - job_name: "node-exporter-work1"
        scrape_interval: 5s
        dns_sd_configs:
          - names: ['node-exporter-0.node-exporter-svc.kube-system']
            port: 9100
            type: A
            refresh_interval: 5s
      - job_name: "node-exporter-work2"
        scrape_interval: 5s
        dns_sd_configs:
          - names: ['node-exporter-1.node-exporter-svc.kube-system']
            port: 9100
            type: A
            refresh_interval: 5s
      - job_name: "node-exporter-work3"
        scrape_interval: 5s
        dns_sd_configs:
          - names: ['node-exporter-2.node-exporter-svc.kube-system']
            port: 9100
            type: A
            refresh_interval: 5s
      - job_name: "node-exporter-work4"
        scrape_interval: 5s
        dns_sd_configs:
          - names: ['node-exporter-3.node-exporter-svc.kube-system']
            port: 9100
            type: A
            refresh_interval: 5s
