FROM grafana/grafana:5.2.0

USER root
RUN apt-get -y update
RUN apt-get -y install procps
#USER wtmp
#COPY docker-entrypoint.sh /
#RUN chmod +x /docker-entrypoint.sh
#CMD ["/bin/bash","-c","/docker-entrypoint.sh"]
