apiVersion: v1
kind: Service
metadata:
  labels:
    monitor: "on"
    class: "system"
    k8s-app: "kube-state-metrics"
  name: "kube-state-metrics"
  namespace: "prometheus"
spec:
  ports:
  - name: https-main
    port: 8443
    targetPort: https-main
  - name: https-self
    port: 9443
    targetPort: https-self
  selector:
    app: kube-state-metrics
